apiVersion: v1
kind: Service
metadata:
  name: techchallenge-fase2-api-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000
  selector:
    app: techchallenge-fase2-api

