name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker build . -t techchallenge-fase3

  deploy:
    runs-on: alpine-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build -t myapp .

    - name: Apply Kubernetes
      run: |
        cd k8s
        kubectl apply -f .
