name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build . -t techchallenge-fase3

  #test:
  #  runs-on: ubuntu-latest
  #  
  #  needs : build
  #  
  #  steps:
  #  - uses: actions/checkout@v4
  #  - uses: actions/setup-node@v3
  #    with:
  #      node-version: 18
  #      cache: 'yarn'
  #  - run: yarn install
  #  - run: yarn test
  #  - run: npx eslint . --ext .js,.jsx,.ts,.tsx

  image:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Docker CLI
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/techchallenge-fase3:latest

  deploy:
    needs: image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }}

    - name: Deploy Kubernetes
      run: |
        cd k8s
        kubectl apply -f .
        



    - name: Check status
      run: |
        kubectl get pods

